services:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - /home/sabrifer/data/database:/var/lib/mysql
    networks:
      inception:
    env_file:
      - .env
    secrets:
      - mariadb_root_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
    env_file:
      - .env
    depends_on:
      - wordpress
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    volumes:
      - /home/sabrifer/data/wordpress:/var/www/html
    networks:
      inception:
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy

networks:
  inception:

secrets:
  mariadb_root_password:
    file: ../secrets/db_root_password.txt