server {

	# Server name
	server_name					sabrifer.42.fr;

    # TLS (HTTPS)
	listen						443 ssl;
	listen						[::]:443 ssl;

	# SSL certificate and key paths
	ssl_certificate				/etc/ssl/certs/sabrifer.42.fr.crt;
	ssl_certificate_key			/etc/ssl/private/sabrifer.42.fr.key;
	ssl_protocols				TLSv1.2 TLSv1.3;

	# Base path
	root						/var/www/wordpress;

	# Default file to serve
	index						index.php;

	# This block tells Nginx to serve the requested file if it exists,
	# otherwise route the request to index.php
    location / {
		# Try to serve file directly, else route to index.php
		try_files 				$uri $uri/ /index.php?$args;
    }

	# PHP handling via php-fpm in the wordpress container
	# when someone requests a .php file, forward it to the PHP processor.
    location ~ \.php$ {
		include 				snippets/fastcgi-php.conf;
		fastcgi_pass 			wordpress:9000;
    }

	# Deny access to dot files for security
    location ~ /\. {
        deny all;
    }
}
